name: CD - Deploy to EKS

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER: otel-cluster
      IMAGE_TAG: latest  # Or use commit SHA if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION

    - name: Install Helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz
        tar -xzf helm-v3.13.0-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm

    - name: Add Helm repo and deploy
      run: |
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm repo update
        helm upgrade --install otel-cd-release open-telemetry/opentelemetry-demo \
          --namespace otel-cd \
          --create-namespace \
          --set default.image.repository=naveedumd/otel-demo \
          --set default.image.tag=${{ env.IMAGE_TAG }} \
          --atomic --wait
