name: CD - Deploy to EKS with Kubectl

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER: otel-demo-cluster

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION

    - name: 🔍 Check cluster connection
      run: kubectl get nodes

    - name: 🏗 Create otel-demo namespace
      run: kubectl create namespace otel-demo --dry-run=client -o yaml | kubectl apply -f -

    - name: 📦 Clone and apply OpenTelemetry manifests
      run: |
        git clone https://github.com/nkafridi1/opentelemetry-demo-FinalProject.git
        cd opentelemetry-demo
        kubectl apply -n otel-demo -f ./kubernetes/opentelemetry-demo.yaml
